#!/bin/bash

echo 'Available Sumos > '
sumos=( 'static-html' 'static-scss' )

for sumo in ${sumos[@]}; do
  echo "> $sumo"
done

makeBasic () {
  read -p "Project Name > " name
  mkdir $name
  mkdir $name/css $name/js
  touch $name/index.html $name/css/app.css $name/js/app.js
  sleep 2
  echo "Created Static $sumo in $name"
}
makeBoiler () {
  echo >> $name/index.html '''<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> A Simple Html</title>
  <link rel="stylesheet" href="css/app.css" type="text/css" media="all">
</head>

<body>

  <h1 style="color: greenyellow;">Nothing To Show Here !</h1>
  <h3 style="color: greenyellow;">Really ?</h3>


  <script src="js/app.js"></script>
</body>

</html>'''

  echo >> $name/css/app.css '''html {
  background-color: black;
}
body {
  font-size: 100%;
  font-family: 'Courier New', Courier, monospace;
  box-sizing: border-box;
}
*,::after,::before {
  box-sizing: initial;
}'''

  echo >> $name/js/app.js '''console.log("Hello, World !")'''
}

read -p "Choose a Sumo > " sumo

if [ $sumo == 'html' ]; then
  makeBasic
  makeBoiler
elif [ $sumo == 'scss' ]; then
  makeBasic
  makeBoiler
  touch $name/css/app.scss

elif [ $sumo == 'node' ]; then
  echo "Under Development"

else
  echo "Error, 404 🤒"
fi
